### ISSUE TITLE
PI stage servo toggle may not respect force quit

### ISSUE THREAD

**Issue by latchr** [QMAPP-mq/qudi#1]
## *What* is affected by this bug?
PI stage motor module

## *When* does this occur?
since it toggles, it might not know the "initial" state

## *Where* on the platform does it happen?
on activate and deactivate

## Expected behavior (i.e. solution)
It should more sensibly try to find the current servo state.

##Other Comments

**Comment by mvbnano** [comment]
Investigated and original code sets servo state, as opposed to toggling. Function name has been clarified.

Additionally, the original code has been shortened with a loop.
