### ISSUE TITLE
useless warning triggered

### ISSUE THREAD

**Issue by mvbnano** [QMAPP-mq/qudi#11]
## *What* is affected by this bug?
This error keeps triggering:

`warning ConfocalScannerInterfaceDummy>set_up_scanner`

## *When* does this occur?
each time 'optimise position' is clicked

## *Where* on the platform does it happen?
Not sure.

## *How* do we replicate the issue?
optimise on a ND

## Expected behavior (i.e. solution)
find whatever is generating the error and kill it

## Other Comments
workflow unaffected

**Comment by mvbnano** [comment]
Located on line 149 of `confocal_scanner_pi_piezo_interfuse.py`

```python
    def set_up_scanner(self, counter_channel = None, photon_source = None, clock_channel = None, scanner_ao_channels = None):
        """ Configures the actual scanner with a given clock.

        TODO this is not technically required, because the spectrometer scanner does not need clock synchronisation.

        @param string counter_channel: if defined, this is the physical channel of the counter
        @param string photon_source: if defined, this is the physical channel where the photons are to count from
        @param string clock_channel: if defined, this specifies the clock for the counter
        @param string scanner_ao_channels: if defined, this specifies the analoque output channels

        @return int: error code (0:OK, -1:error)
        """
        self.log.warning('ConfocalScannerInterfaceDummy>set_up_scanner')
        return 0
```

@latchr Do you know what this function is for? It's getting called often, but does nothing. I think we do not need to call it, and can at least silence the warning.

**Comment by latchr** [comment]
The log.warning message is not needed. It is lingering there from an
initial copy from the dummy hardware file. Delete it but keep the return 0

**Comment by mvbnano** [comment]
Thanks mate. warning removed, branch ready to merge.
