### ISSUE TITLE
Identification of PI stage error

### ISSUE THREAD

**Issue by mvbnano** [QMAPP-mq/qudi#2]
## *What* is affected by this bug?
Connection to the PI stage can not be established if the Thorlabs APT motor is also connected (physically) to the PC.

## *When* does this occur?
Error is thrown when attempting a connection to the PI stage.

## *Where* on the platform does it happen?
On activate

## *How* do we replicate the issue?
Have both the PI stage and the Thorlabs APT motor connected (physically) to the PC by USB.

## Expected behavior (i.e. solution)
Code should check gor the PI stage name, as opposed to choosing the first in the list.

## Other Comments
Conduct works on branch `pi_usb_digital_control`

**Comment by latchr** [comment]
This is fixed by looking at the list of devices and searching for only those with "PI" in their name.
