### ISSUE TITLE
pyusb

### ISSUE THREAD

**Issue by mvbnano** [QMAPP-mq/qudi#22]
With the addition of code (in development) for the New Focus piezo screws (on branch `dev_nefocus_screws`) the package **pyusb** is required. This does not appear to be in the qudi environment. Will it be required to add this to the environment generation code (staying in the `dev_nefocus_screws` branch)?

**Comment by mvbnano** [comment]
@latchr does this only need to be updated in:

- [ ] ```conda-env-linx64-qt5.yml```
- [ ] ```conda-env-win8-qt5.yml```

And because we did not have any version problems, it should just be the current version I suppose.

**Comment by latchr** [comment]
Yes. Then we should probably send an email to qudi-announce

**Comment by mvbnano** [comment]
I will add this on the branch ```dev_newfocus_screws``` unless advised otherwise.
