### ISSUE TITLE
Add loaded icon for hardware modules

### ISSUE THREAD

**Issue by BGNorton** [QMAPP-mq/qudi#23]
## *What* is affected by this bug?
The home screen of the Qudi GUI.

## *When* does this occur?
All the time.

## *How* do we replicate the issue?
open up the hardware tab of the home screen

## Expected behavior (i.e. solution)
have a simple icon/indicator that indicates whether a hardware module has been loaded in or not.

## Other Comments
This will stop confusion about whether a module has been loaded which ultimately throws errors.

**Comment by mvbnano** [comment]
Good idea @BGNorton 

@latchr suggested that we could 'grey out' the reload module button if the module has not been loaded

**Comment by latchr** [comment]
There is currently a text string g under the load button which changes from "not loaded" to "idle" (and even to "active" or something when the module is executing actions). This is not super clear and I like the suggestion of some visual icon/indicator.

**Comment by mvbnano** [comment]
This feature has been coded and a pull request is pending, see Ulm-IQO/qudi#306

**Comment by mvbnano** [comment]
Pull request has been approved, Ulm-IQO/qudi#306 , and `master` has been merged into `deployed_teaching_labs`.
