### ISSUE TITLE
set_wavelength in m2 laser module is broken

### ISSUE THREAD

**Issue by latchr** [QMAPP-mq/qudi#3]
## *What* is affected by this bug?
cannot set wavelength in msquared laser module

## *When* does this occur?
try to set it 

## Expected behavior (i.e. solution)
set the wavelength

## Other Comments

It complains about having 3 parameters passed to _lock_wavelength but only expecting 2.

**Comment by mvbnano** [comment]
**UNTESTED**

Believe issue has been fixed by completing the wavelength locking function.

For completeness, a get wavelength lock status function has also been created, but it currently unused.

**Comment by mvbnano** [comment]
```python
    def _set_wavelength_lock(self, target_state):
        """ Set the wavelength lock either `on' or `off'

            @return bool status of the wavelength lock
        """
```

```python
    def _get_wavelength_lock(self, target_state):
        """ Get the wavelength lock status

            @return bool status of the wavelength lock
        """
```

**Comment by mvbnano** [comment]
`dev_m_squared` tested and working

**Comment by mvbnano** [comment]
development branch successfully merged into `deployed_siv_upconversion`
