### ISSUE TITLE
docstring formatting

### ISSUE THREAD

**Issue by mvbnano** [QMAPP-mq/qudi#30]
## *What* is affected by this bug?
All docstrings, class and function alike, should have consistent docstrings that are compatible with doxygen.

## *When* does this occur?
In all our dev branches.

## *Where* on the platform does it happen?
All class docstrings and all function docstrings.

## Other Comments
Expected behaviour information to follow.

**Comment by latchr** [comment]
Needs to start with a one line short description then, a blank line.

For methods, need to have consistent param and return.
